import { IoIcons } from "../../icon";

    const productData = [
    {
        all_products: [
    {
        id: 1 ,
        prod_title: "Margherita",
        prod_img:"https://i.ibb.co/T2d5K5h/margherita-pizza.jpg",
        IconFilled: <IoIcons.FilledStar />,
        IconOutline: <IoIcons.OutlineStar />,
        prod_price_1: 15.25,
        prod_price_2: 6.30,
        prod_desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia distinctio ipsa illum sequi vero ratione nam voluptates",
    },
    {
        id: 2,
        prod_title: "Potato Pizza",
        prod_img:"https://i.ibb.co/fNbv7vt/potato-salad.jpg",
        IconFilled: <IoIcons.FilledStar />,
        IconOutline: <IoIcons.OutlineStar />,
        prod_price_1: 12.20,
        prod_price_2: 3.30,
        prod_desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia distinctio ipsa illum sequi vero ratione nam voluptates",
    },
    {
        id:3,
        IconFilled: <IoIcons.FilledStar />,
        IconOutline: <IoIcons.OutlineStar />,
        prod_title: "Wagyu burger",
        prod_desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia distinctio ipsa illum sequi vero ratione nam voluptates, modi nobis nihil velit deleniti consectetur libero dolorem ab ea, placeat iste consequuntur sint? Omnis aliquam vel ab.",
        prod_price_1: 10.55,
        prod_price_2: 8.50,
        prod_img:"https://i.ibb.co/BT0db57/wagyu-burger.jpg",
    },
    {
        id:4,
        prod_title: "Hawaiian Pizza",
        prod_img:"https://i.ibb.co/zmX9bpq/hawaiian-pizza.jpg",
        IconFilled: <IoIcons.FilledStar />,
        IconOutline: <IoIcons.OutlineStar />,
        prod_price_1: 12.25,
        prod_price_2: 5.30,
        prod_desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia distinctio ipsa illum sequi vero ratione nam voluptates",
    },
    {
        id:5,
        prod_title: "Pepperoni",
        prod_img:"https://i.ibb.co/WxPG4jL/pepperoni-piza.jpg",
        IconFilled: <IoIcons.FilledStar />,
        IconOutline: <IoIcons.OutlineStar />,
        prod_price_1: 11.30,
        prod_price_2: 4.30,
        prod_desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia distinctio ipsa illum sequi vero ratione nam voluptates",
    },
    {
        id:6,
        IconFilled: <IoIcons.FilledStar />,
        IconOutline: <IoIcons.OutlineStar />,
        prod_title: "Chicken Sharwama",
        prod_desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia distinctio ipsa illum sequi vero ratione nam voluptates, modi nobis nihil velit deleniti consectetur libero dolorem ab ea, placeat iste consequuntur sint? Omnis aliquam vel ab.",
        prod_price_1: 10.25,
        prod_price_2: 6.25,
        prod_img:"https://i.ibb.co/YNM8Lvy/chicken-veggie-sharwama.jpg",
    },
    {
        id:7,
        prod_title: "Mediterranean",
        prod_img:"https://i.ibb.co/4fjjvHN/mediterranean-piza.jpg",
        IconFilled: <IoIcons.FilledStar />,
        IconOutline: <IoIcons.OutlineStar />,
        prod_price_1: 12.25,
        prod_price_2: 7.15,
        prod_desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia distinctio ipsa illum sequi vero ratione nam voluptates",
    },
    {
        id:8,
        IconFilled: <IoIcons.FilledStar />,
        IconOutline: <IoIcons.OutlineStar />,
        prod_title: "Souvlaki Sharwama",
        prod_desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia distinctio ipsa illum sequi vero ratione nam voluptates",
        prod_price_1: 12.60,
        prod_price_2: 8.60,
        prod_img:"https://i.ibb.co/Qf6ZnYn/beef-souvlaki-sharwarma.jpg",
    },
    {
        id:9,
        IconFilled: <IoIcons.FilledStar />,
        IconOutline: <IoIcons.OutlineStar />,
        prod_title: "Black Bean Burger",
        prod_desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia distinctio ipsa illum sequi vero ratione nam voluptates",
        prod_price_1: 12.60,
        prod_price_2: 8.60,
        prod_img:"https://i.ibb.co/FBjF7vr/black-bean-burger.jpg",
    },
    {
        id:10,
        IconFilled: <IoIcons.FilledStar />,
        IconOutline: <IoIcons.OutlineStar />,
        prod_title: "Beef Burger",
        prod_desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia distinctio ipsa illum sequi vero ratione nam voluptates",
        prod_price_1: 12.60,
        prod_price_2: 8.60,
        prod_img:"https://i.ibb.co/ZXGXnmq/beef-burger.jpg",
    },
    {
        id:11,
        IconFilled: <IoIcons.FilledStar />,
        IconOutline: <IoIcons.OutlineStar />,
        prod_title: "Platter Sushi",
        prod_desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia distinctio ipsa illum sequi vero ratione nam voluptates",
        prod_price_1: 10.55,
        prod_price_2: 8.50,
        prod_img:"https://i.ibb.co/wYy9rgG/sushi-7.jpg",
    },
    {
        id:12,
        IconFilled: <IoIcons.FilledStar />,
        IconOutline: <IoIcons.OutlineStar />,
        prod_title: "Pasta Salad",
        prod_desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia distinctio ipsa illum sequi vero ratione nam voluptates",
        prod_price_1: 10.55,
        prod_price_2: 4.50,
        prod_img:"https://i.ibb.co/sHg6kmb/pasta-salad.jpg",
    },
    {
        id:13,
        IconFilled: <IoIcons.FilledStar />,
        IconOutline: <IoIcons.OutlineStar />,
        prod_title: "Burrito Sharwama",
        prod_desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia distinctio ipsa illum sequi vero ratione nam voluptates",
        prod_price_1: 10.25,
        prod_price_2: 6.25,
        prod_img:"https://i.ibb.co/YcN25mF/burrito-grilled-chicken-sharwama.jpg",
    },
    {
        id:14,
        IconFilled: <IoIcons.FilledStar />,
        IconOutline: <IoIcons.OutlineStar />,
        prod_title: "Mozarella Pizza",
        prod_desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia distinctio ipsa illum sequi vero ratione nam voluptates",
        prod_price_1: 7.25,
        prod_price_2: 3.25,
        prod_img:"https://i.ibb.co/R68d2Mt/mozzarella-basil-pizza.jpg",
    },
    {
        id:15,
        IconFilled: <IoIcons.FilledStar />,
        IconOutline: <IoIcons.OutlineStar />,
        prod_title: "Creamy Fruit Salad",
        prod_desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia distinctio ipsa illum sequi vero ratione nam voluptates",
        prod_price_1: 11.35,
        prod_price_2: 6.25,
        prod_img:"https://i.ibb.co/V2mDSCm/creamy-fresh-fruit-salad.jpg",
    },
    {
        id:16,
        IconFilled: <IoIcons.FilledStar />,
        IconOutline: <IoIcons.OutlineStar />,
        prod_title: "Spicy Bread Sharwama",
        prod_desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia distinctio ipsa illum sequi vero ratione nam voluptates",
        prod_price_1: 11.35,
        prod_price_2: 6.25,
        prod_img:"https://i.ibb.co/JB20R85/spicy-bread-sharwama.jpg",
    },
    {
        id:17,
        IconFilled: <IoIcons.FilledStar />,
        IconOutline: <IoIcons.OutlineStar />,
        prod_title: "Sushi Salmone",
        prod_desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia distinctio ipsa illum sequi vero ratione nam voluptates, modi nobis nihil velit deleniti consectetur libero dolorem ab ea, placeat iste consequuntur sint? Omnis aliquam vel ab.",
        prod_price_1: 13.45,
        prod_price_2: 5.30,
        prod_img:"https://i.ibb.co/pRX8335/sushi-japanese-salmon.jpg",
    },
    {
        id:18,
        IconFilled: <IoIcons.FilledStar />,
        IconOutline: <IoIcons.OutlineStar />,
        prod_title: "Caprese Pizza",
        prod_desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia distinctio ipsa illum sequi vero ratione nam voluptates, modi nobis nihil velit deleniti consectetur libero dolorem ab ea, placeat iste consequuntur sint? Omnis aliquam vel ab.",
        prod_price_1: 13.45,
        prod_price_2: 5.30,
        prod_img:"https://i.ibb.co/2gS8Tjy/caprese-pizza.jpg",
    },
    {
        id:19,
        IconFilled: <IoIcons.FilledStar />,
        IconOutline: <IoIcons.OutlineStar />,
        prod_title: "Bacon kobe burger",
        prod_desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia distinctio ipsa illum sequi vero ratione nam voluptates",
        prod_price_1: 10.55,
        prod_price_2: 4.50,
        prod_img:"https://i.ibb.co/pWvJHmW/bacon-kobe-beef-burger.jpg",
    },
    {
        id:20,
        IconFilled: <IoIcons.FilledStar />,
        IconOutline: <IoIcons.OutlineStar />,
        prod_title: "Chicken Breast Salad",
        prod_desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia distinctio ipsa illum sequi vero ratione nam voluptates",
        prod_price_1: 10.55,
        prod_price_2: 4.50,
        prod_img:"https://i.ibb.co/j6QvPpJ/chicken-breast-salad-1.jpg",
    },
    {
        id:21,
        IconFilled: <IoIcons.FilledStar />,
        IconOutline: <IoIcons.OutlineStar />,
        prod_title: "Turkey burger",
        prod_desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia distinctio ipsa illum sequi vero ratione nam voluptates",
        prod_price_1: 10.55,
        prod_price_2: 8.50,
        prod_img:"https://i.ibb.co/MppZXL1/turkey-burger.jpg",
    },
    {
        id:22,
        IconFilled: <IoIcons.FilledStar />,
        IconOutline: <IoIcons.OutlineStar />,
        prod_title: "Salmone Sushi",
        prod_desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia distinctio ipsa illum sequi vero ratione nam voluptates",
        prod_price_1: 10.55,
        prod_price_2: 8.50,
        prod_img:"https://i.ibb.co/ncH4Zh2/sushi-4.jpg",
    },
    {
        id:23,
        IconFilled: <IoIcons.FilledStar />,
        IconOutline: <IoIcons.OutlineStar />,
        prod_title: "Chicken breast",
        prod_desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia distinctio ipsa illum sequi vero ratione nam voluptates, modi nobis nihil velit deleniti consectetur libero dolorem ab ea, placeat iste consequuntur sint? Omnis aliquam vel ab.",
        prod_price_1: 12.25,
        prod_price_2: 5.35,
        prod_img:"https://i.ibb.co/dBGWdT7/chicken-breast-salad-2.jpg",
    },
    {
        id:24,
        IconFilled: <IoIcons.FilledStar />,
        IconOutline: <IoIcons.OutlineStar />,
        prod_title: "Mini Burger",
        prod_desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia distinctio ipsa illum sequi vero ratione nam voluptates",
        prod_price_1: 12.25,
        prod_price_2: 3.75,
        prod_img:"https://i.ibb.co/Swb7Wnx/mini-burger.jpg",
    },
    {
        id:25,
        IconFilled: <IoIcons.FilledStar />,
        IconOutline: <IoIcons.OutlineStar />,
        prod_title: "Japanese Sushi",
        prod_desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia distinctio ipsa illum sequi vero ratione nam voluptates",
        prod_price_1: 10.25,
        prod_price_2: 4.25,
        prod_img:"https://i.ibb.co/QHdV5KY/sushi-4.jpg",
    },

        ],
        pizza: [
    {
        id:1,
        prod_title: "Margherita",
        prod_img:"https://i.ibb.co/T2d5K5h/margherita-pizza.jpg",
        IconFilled: <IoIcons.FilledStar />,
        IconOutline: <IoIcons.OutlineStar />,
        prod_price_1: 15.25,
        prod_price_2: 6.30,
        prod_desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia distinctio ipsa illum sequi vero ratione nam voluptates",
    },
    {
        id:2,
        prod_title: "Potato Pizza",
        prod_img:"https://i.ibb.co/fNbv7vt/potato-salad.jpg",
        IconFilled: <IoIcons.FilledStar />,
        IconOutline: <IoIcons.OutlineStar />,
        prod_price_1: 12.20,
        prod_price_2: 3.30,
        prod_desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia distinctio ipsa illum sequi vero ratione nam voluptates",
    },
    {
        id:18,
        IconFilled: <IoIcons.FilledStar />,
        IconOutline: <IoIcons.OutlineStar />,
        prod_title: "Caprese Pizza",
        prod_desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia distinctio ipsa illum sequi vero ratione nam voluptates, modi nobis nihil velit deleniti consectetur libero dolorem ab ea, placeat iste consequuntur sint? Omnis aliquam vel ab.",
        prod_price_1: 13.45,
        prod_price_2: 5.30,
        prod_img:"https://i.ibb.co/2gS8Tjy/caprese-pizza.jpg",
    },
    {
        id:7,
        prod_title: "Mediterranean",
        prod_img:"https://i.ibb.co/4fjjvHN/mediterranean-piza.jpg",
        IconFilled: <IoIcons.FilledStar />,
        IconOutline: <IoIcons.OutlineStar />,
        prod_price_1: 12.25,
        prod_price_2: 7.15,
        prod_desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia distinctio ipsa illum sequi vero ratione nam voluptates, modi nobis nihil velit deleniti consectetur libero dolorem ab ea, placeat iste consequuntur sint? Omnis aliquam vel ab.",
    },
    {
        id:14,
        IconFilled: <IoIcons.FilledStar />,
        IconOutline: <IoIcons.OutlineStar />,
        prod_title: "Mozarella Pizza",
        prod_desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia distinctio ipsa illum sequi vero ratione nam voluptates, modi nobis nihil velit deleniti consectetur libero dolorem ab ea, placeat iste consequuntur sint? Omnis aliquam vel ab.",
        prod_price_1: 7.25,
        prod_price_2: 3.25,
        prod_img:"https://i.ibb.co/R68d2Mt/mozzarella-basil-pizza.jpg",
    },
    {
        id:14,
        IconFilled: <IoIcons.FilledStar />,
        IconOutline: <IoIcons.OutlineStar />,
        prod_title: "Mozarella Pizza",
        prod_desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia distinctio ipsa illum sequi vero ratione nam voluptates, modi nobis nihil velit deleniti consectetur libero dolorem ab ea, placeat iste consequuntur sint? Omnis aliquam vel ab.",
        prod_price_1: 7.25,
        prod_price_2: 3.25,
        prod_img:"https://i.ibb.co/R68d2Mt/mozzarella-basil-pizza.jpg",
    },
    {
        id:4,
        prod_title: "Hawaiian Pizza",
        prod_img:"https://i.ibb.co/zmX9bpq/hawaiian-pizza.jpg",
        IconFilled: <IoIcons.FilledStar />,
        IconOutline: <IoIcons.OutlineStar />,
        prod_price_1: 12.25,
        prod_price_2: 5.30,
        prod_desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia distinctio ipsa illum sequi vero ratione nam voluptates, modi nobis nihil velit deleniti consectetur libero dolorem ab ea, placeat iste consequuntur sint? Omnis aliquam vel ab.",
    },
    {
        id:5,
        prod_title: "Pepperoni",
        prod_img:"https://i.ibb.co/WxPG4jL/pepperoni-piza.jpg",
        IconFilled: <IoIcons.FilledStar />,
        IconOutline: <IoIcons.OutlineStar />,
        prod_price_1: 11.30,
        prod_price_2: 4.30,
        prod_desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia distinctio ipsa illum sequi vero ratione nam voluptates, modi nobis nihil velit deleniti consectetur libero dolorem ab ea, placeat iste consequuntur sint? Omnis aliquam vel ab.",
    },

    ],
        sushi: [
        {
            id:25,
            IconFilled: <IoIcons.FilledStar />,
            IconOutline: <IoIcons.OutlineStar />,
            prod_title: "Japanese Sushi",
            prod_desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia distinctio ipsa illum sequi vero ratione nam voluptates, modi nobis nihil velit deleniti consectetur libero dolorem ab ea, placeat iste consequuntur sint? Omnis aliquam vel ab.",
            prod_price_1: 10.25,
            prod_price_2: 4.25,
            prod_img:"https://i.ibb.co/QHdV5KY/sushi-4.jpg",
        },
        {
            id:22,
            IconFilled: <IoIcons.FilledStar />,
            IconOutline: <IoIcons.OutlineStar />,
            prod_title: "Salmone Sushi",
            prod_desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia distinctio ipsa illum sequi vero ratione nam voluptates",
            prod_price_1: 10.55,
            prod_price_2: 8.50,
            prod_img:"https://i.ibb.co/ncH4Zh2/sushi-4.jpg",
        },
        {
            id:11,
            IconFilled: <IoIcons.FilledStar />,
            IconOutline: <IoIcons.OutlineStar />,
            prod_title: "Platter Sushi",
            prod_desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia distinctio ipsa illum sequi vero ratione nam voluptates",
            prod_price_1: 10.55,
            prod_price_2: 8.50,
            prod_img:"https://i.ibb.co/wYy9rgG/sushi-7.jpg",
        },
        {
            id:25,
            IconFilled: <IoIcons.FilledStar />,
            IconOutline: <IoIcons.OutlineStar />,
            prod_title: "Japanese Sushi",
            prod_desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia distinctio ipsa illum sequi vero ratione nam voluptates, modi nobis nihil velit deleniti consectetur libero dolorem ab ea, placeat iste consequuntur sint? Omnis aliquam vel ab.",
            prod_price_1: 10.25,
            prod_price_2: 4.25,
            prod_img:"https://i.ibb.co/QHdV5KY/sushi-4.jpg",
        },
        {
            id:22,
            IconFilled: <IoIcons.FilledStar />,
            IconOutline: <IoIcons.OutlineStar />,
            prod_title: "Salmone Sushi",
            prod_desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia distinctio ipsa illum sequi vero ratione nam voluptates",
            prod_price_1: 10.55,
            prod_price_2: 8.50,
            prod_img:"https://i.ibb.co/ncH4Zh2/sushi-4.jpg",
        },
        {
            id:11,
            IconFilled: <IoIcons.FilledStar />,
            IconOutline: <IoIcons.OutlineStar />,
            prod_title: "Platter Sushi",
            prod_desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia distinctio ipsa illum sequi vero ratione nam voluptates",
            prod_price_1: 10.55,
            prod_price_2: 8.50,
            prod_img:"https://i.ibb.co/wYy9rgG/sushi-7.jpg",
        },
        {
            id:25,
            IconFilled: <IoIcons.FilledStar />,
            IconOutline: <IoIcons.OutlineStar />,
            prod_title: "Japanese Sushi",
            prod_desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia distinctio ipsa illum sequi vero ratione nam voluptates, modi nobis nihil velit deleniti consectetur libero dolorem ab ea, placeat iste consequuntur sint? Omnis aliquam vel ab.",
            prod_price_1: 10.25,
            prod_price_2: 4.25,
            prod_img:"https://i.ibb.co/QHdV5KY/sushi-4.jpg",
        },
        {
            id:22,
            IconFilled: <IoIcons.FilledStar />,
            IconOutline: <IoIcons.OutlineStar />,
            prod_title: "Salmone Sushi",
            prod_desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia distinctio ipsa illum sequi vero ratione nam voluptates",
            prod_price_1: 10.55,
            prod_price_2: 8.50,
            prod_img:"https://i.ibb.co/ncH4Zh2/sushi-4.jpg",
        },
        {
            id:11,
            IconFilled: <IoIcons.FilledStar />,
            IconOutline: <IoIcons.OutlineStar />,
            prod_title: "Platter Sushi",
            prod_desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia distinctio ipsa illum sequi vero ratione nam voluptates",
            prod_price_1: 10.55,
            prod_price_2: 8.50,
            prod_img:"https://i.ibb.co/wYy9rgG/sushi-7.jpg",
        },
        ],

        salad: [
        {
            id:15,
            IconFilled: <IoIcons.FilledStar />,
            IconOutline: <IoIcons.OutlineStar />,
            prod_title: "Creamy Fruit Salad",
            prod_desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia distinctio ipsa illum sequi vero ratione nam voluptates, modi nobis nihil velit deleniti consectetur libero dolorem ab ea, placeat iste consequuntur sint? Omnis aliquam vel ab.",
            prod_price_1: 11.35,
            prod_price_2: 6.25,
            prod_img:"https://i.ibb.co/V2mDSCm/creamy-fresh-fruit-salad.jpg",
        },
        {
            id:20,
            IconFilled: <IoIcons.FilledStar />,
            IconOutline: <IoIcons.OutlineStar />,
            prod_title: "Chicken Breast Salad",
            prod_desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia distinctio ipsa illum sequi vero ratione nam voluptates",
            prod_price_1: 10.55,
            prod_price_2: 4.50,
            prod_img:"https://i.ibb.co/j6QvPpJ/chicken-breast-salad-1.jpg",
        },
        {
            id:12,
            IconFilled: <IoIcons.FilledStar />,
            IconOutline: <IoIcons.OutlineStar />,
            prod_title: "Pasta Salad",
            prod_desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia distinctio ipsa illum sequi vero ratione nam voluptates",
            prod_price_1: 10.55,
            prod_price_2: 4.50,
            prod_img:"https://i.ibb.co/sHg6kmb/pasta-salad.jpg",
        },
        {
            id:15,
            IconFilled: <IoIcons.FilledStar />,
            IconOutline: <IoIcons.OutlineStar />,
            prod_title: "Creamy Fruit Salad",
            prod_desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia distinctio ipsa illum sequi vero ratione nam voluptates, modi nobis nihil velit deleniti consectetur libero dolorem ab ea, placeat iste consequuntur sint? Omnis aliquam vel ab.",
            prod_price_1: 11.35,
            prod_price_2: 6.25,
            prod_img:"https://i.ibb.co/V2mDSCm/creamy-fresh-fruit-salad.jpg",
        },
        {
            id:20,
            IconFilled: <IoIcons.FilledStar />,
            IconOutline: <IoIcons.OutlineStar />,
            prod_title: "Chicken Breast Salad",
            prod_desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia distinctio ipsa illum sequi vero ratione nam voluptates",
            prod_price_1: 10.55,
            prod_price_2: 4.50,
            prod_img:"https://i.ibb.co/j6QvPpJ/chicken-breast-salad-1.jpg",
        },
        {
            id:12,
            IconFilled: <IoIcons.FilledStar />,
            IconOutline: <IoIcons.OutlineStar />,
            prod_title: "Pasta Salad",
            prod_desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia distinctio ipsa illum sequi vero ratione nam voluptates",
            prod_price_1: 10.55,
            prod_price_2: 4.50,
            prod_img:"https://i.ibb.co/sHg6kmb/pasta-salad.jpg",
        },
        {
            id:15,
            IconFilled: <IoIcons.FilledStar />,
            IconOutline: <IoIcons.OutlineStar />,
            prod_title: "Creamy Fruit Salad",
            prod_desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia distinctio ipsa illum sequi vero ratione nam voluptates, modi nobis nihil velit deleniti consectetur libero dolorem ab ea, placeat iste consequuntur sint? Omnis aliquam vel ab.",
            prod_price_1: 11.35,
            prod_price_2: 6.25,
            prod_img:"https://i.ibb.co/V2mDSCm/creamy-fresh-fruit-salad.jpg",
        },
        {
            id:20,
            IconFilled: <IoIcons.FilledStar />,
            IconOutline: <IoIcons.OutlineStar />,
            prod_title: "Chicken Breast Salad",
            prod_desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia distinctio ipsa illum sequi vero ratione nam voluptates",
            prod_price_1: 10.55,
            prod_price_2: 4.50,
            prod_img:"https://i.ibb.co/j6QvPpJ/chicken-breast-salad-1.jpg",
        },
        {
            id:12,
            IconFilled: <IoIcons.FilledStar />,
            IconOutline: <IoIcons.OutlineStar />,
            prod_title: "Pasta Salad",
            prod_desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia distinctio ipsa illum sequi vero ratione nam voluptates",
            prod_price_1: 10.55,
            prod_price_2: 4.50,
            prod_img:"https://i.ibb.co/sHg6kmb/pasta-salad.jpg",
        },
        ],

        burger: [
            {
            id:24,
            IconFilled: <IoIcons.FilledStar />,
            IconOutline: <IoIcons.OutlineStar />,
            prod_title: "Mini Burger",
            prod_desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia distinctio ipsa illum sequi vero ratione nam voluptates, modi nobis nihil velit deleniti consectetur libero dolorem ab ea, placeat iste consequuntur sint? Omnis aliquam vel ab.",
            prod_price_1: 12.25,
            prod_price_2: 3.75,
            prod_img:"https://i.ibb.co/Swb7Wnx/mini-burger.jpg",
        },
        {
            id:21,
            IconFilled: <IoIcons.FilledStar />,
            IconOutline: <IoIcons.OutlineStar />,
            prod_title: "Turkey burger",
            prod_desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia distinctio ipsa illum sequi vero ratione nam voluptates, modi nobis nihil velit deleniti consectetur libero dolorem ab ea, placeat iste consequuntur sint? Omnis aliquam vel ab.",
            prod_price_1: 10.55,
            prod_price_2: 8.50,
            prod_img:"https://i.ibb.co/MppZXL1/turkey-burger.jpg",
        },
        {
            id:9,
            IconFilled: <IoIcons.FilledStar />,
            IconOutline: <IoIcons.OutlineStar />,
            prod_title: "Black Bean Burger",
            prod_desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia distinctio ipsa illum sequi vero ratione nam voluptates",
            prod_price_1: 12.60,
            prod_price_2: 8.60,
            prod_img:"https://i.ibb.co/FBjF7vr/black-bean-burger.jpg",
        },
        {
            id:10,
            IconFilled: <IoIcons.FilledStar />,
            IconOutline: <IoIcons.OutlineStar />,
            prod_title: "Beef Burger",
            prod_desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia distinctio ipsa illum sequi vero ratione nam voluptates",
            prod_price_1: 12.60,
            prod_price_2: 8.60,
            prod_img:"https://i.ibb.co/ZXGXnmq/beef-burger.jpg",
        },
        {
            id:3,
            IconFilled: <IoIcons.FilledStar />,
            IconOutline: <IoIcons.OutlineStar />,
            prod_title: "Wagyu burger",
            prod_desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia distinctio ipsa illum sequi vero ratione nam voluptates, modi nobis nihil velit deleniti consectetur libero dolorem ab ea, placeat iste consequuntur sint? Omnis aliquam vel ab.",
            prod_price_1: 10.55,
            prod_price_2: 8.50,
            prod_img:"https://i.ibb.co/BT0db57/wagyu-burger.jpg",
        },
        {
            id:3,
            IconFilled: <IoIcons.FilledStar />,
            IconOutline: <IoIcons.OutlineStar />,
            prod_title: "Wagyu burger",
            prod_desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia distinctio ipsa illum sequi vero ratione nam voluptates, modi nobis nihil velit deleniti consectetur libero dolorem ab ea, placeat iste consequuntur sint? Omnis aliquam vel ab.",
            prod_price_1: 10.55,
            prod_price_2: 8.50,
            prod_img:"https://i.ibb.co/BT0db57/wagyu-burger.jpg",
        },
        {
            id:3,
            IconFilled: <IoIcons.FilledStar />,
            IconOutline: <IoIcons.OutlineStar />,
            prod_title: "Wagyu burger",
            prod_desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia distinctio ipsa illum sequi vero ratione nam voluptates, modi nobis nihil velit deleniti consectetur libero dolorem ab ea, placeat iste consequuntur sint? Omnis aliquam vel ab.",
            prod_price_1: 10.55,
            prod_price_2: 8.50,
            prod_img:"https://i.ibb.co/BT0db57/wagyu-burger.jpg",
        },
        {
            id:3,
            IconFilled: <IoIcons.FilledStar />,
            IconOutline: <IoIcons.OutlineStar />,
            prod_title: "Wagyu burger",
            prod_desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia distinctio ipsa illum sequi vero ratione nam voluptates, modi nobis nihil velit deleniti consectetur libero dolorem ab ea, placeat iste consequuntur sint? Omnis aliquam vel ab.",
            prod_price_1: 10.55,
            prod_price_2: 8.50,
            prod_img:"https://i.ibb.co/BT0db57/wagyu-burger.jpg",
        },
        {
            id:3,
            IconFilled: <IoIcons.FilledStar />,
            IconOutline: <IoIcons.OutlineStar />,
            prod_title: "Wagyu burger",
            prod_desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia distinctio ipsa illum sequi vero ratione nam voluptates, modi nobis nihil velit deleniti consectetur libero dolorem ab ea, placeat iste consequuntur sint? Omnis aliquam vel ab.",
            prod_price_1: 10.55,
            prod_price_2: 8.50,
            prod_img:"https://i.ibb.co/BT0db57/wagyu-burger.jpg",
        },
        {
            id:3,
            IconFilled: <IoIcons.FilledStar />,
            IconOutline: <IoIcons.OutlineStar />,
            prod_title: "Wagyu burger",
            prod_desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia distinctio ipsa illum sequi vero ratione nam voluptates, modi nobis nihil velit deleniti consectetur libero dolorem ab ea, placeat iste consequuntur sint? Omnis aliquam vel ab.",
            prod_price_1: 10.55,
            prod_price_2: 8.50,
            prod_img:"https://i.ibb.co/BT0db57/wagyu-burger.jpg",
        },
        ],

        sharwama: [
        {
            id:8,
            IconFilled: <IoIcons.FilledStar />,
            IconOutline: <IoIcons.OutlineStar />,
            prod_title: "Souvlaki Sharwama",
            prod_desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia distinctio ipsa illum sequi vero ratione nam voluptates, modi nobis nihil velit deleniti consectetur libero dolorem ab ea, placeat iste consequuntur sint? Omnis aliquam vel ab.",
            prod_price_1: 12.60,
            prod_price_2: 8.60,
            prod_img:"https://i.ibb.co/Qf6ZnYn/beef-souvlaki-sharwarma.jpg",
        },
        {
            id:16,
            IconFilled: <IoIcons.FilledStar />,
            IconOutline: <IoIcons.OutlineStar />,
            prod_title: "Spicy Bread Sharwama",
            prod_desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia distinctio ipsa illum sequi vero ratione nam voluptates",
            prod_price_1: 11.35,
            prod_price_2: 6.25,
            prod_img:"https://i.ibb.co/JB20R85/spicy-bread-sharwama.jpg",
        },
        {
            id:13,
            IconFilled: <IoIcons.FilledStar />,
            IconOutline: <IoIcons.OutlineStar />,
            prod_title: "Burrito Sharwama",
            prod_desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia distinctio ipsa illum sequi vero ratione nam voluptates, modi nobis nihil velit deleniti consectetur libero dolorem ab ea, placeat iste consequuntur sint? Omnis aliquam vel ab.",
            prod_price_1: 10.25,
            prod_price_2: 6.25,
            prod_img:"https://i.ibb.co/YcN25mF/burrito-grilled-chicken-sharwama.jpg",
        },
        {
            id:6,
            IconFilled: <IoIcons.FilledStar />,
            IconOutline: <IoIcons.OutlineStar />,
            prod_title: "Chicken Sharwama",
            prod_desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia distinctio ipsa illum sequi vero ratione nam voluptates, modi nobis nihil velit deleniti consectetur libero dolorem ab ea, placeat iste consequuntur sint? Omnis aliquam vel ab.",
            prod_price_1: 10.25,
            prod_price_2: 6.25,
            prod_img:"https://i.ibb.co/YNM8Lvy/chicken-veggie-sharwama.jpg",
        },
        {
            id:6,
            IconFilled: <IoIcons.FilledStar />,
            IconOutline: <IoIcons.OutlineStar />,
            prod_title: "Chicken Sharwama",
            prod_desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia distinctio ipsa illum sequi vero ratione nam voluptates, modi nobis nihil velit deleniti consectetur libero dolorem ab ea, placeat iste consequuntur sint? Omnis aliquam vel ab.",
            prod_price_1: 10.25,
            prod_price_2: 6.25,
            prod_img:"https://i.ibb.co/YNM8Lvy/chicken-veggie-sharwama.jpg",
        },
        {
            id:6,
            IconFilled: <IoIcons.FilledStar />,
            IconOutline: <IoIcons.OutlineStar />,
            prod_title: "Chicken Sharwama",
            prod_desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia distinctio ipsa illum sequi vero ratione nam voluptates, modi nobis nihil velit deleniti consectetur libero dolorem ab ea, placeat iste consequuntur sint? Omnis aliquam vel ab.",
            prod_price_1: 10.25,
            prod_price_2: 6.25,
            prod_img:"https://i.ibb.co/YNM8Lvy/chicken-veggie-sharwama.jpg",
        },
        {
            id:6,
            IconFilled: <IoIcons.FilledStar />,
            IconOutline: <IoIcons.OutlineStar />,
            prod_title: "Chicken Sharwama",
            prod_desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia distinctio ipsa illum sequi vero ratione nam voluptates, modi nobis nihil velit deleniti consectetur libero dolorem ab ea, placeat iste consequuntur sint? Omnis aliquam vel ab.",
            prod_price_1: 10.25,
            prod_price_2: 6.25,
            prod_img:"https://i.ibb.co/YNM8Lvy/chicken-veggie-sharwama.jpg",
        },
        {
            id:6,
            IconFilled: <IoIcons.FilledStar />,
            IconOutline: <IoIcons.OutlineStar />,
            prod_title: "Chicken Sharwama",
            prod_desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia distinctio ipsa illum sequi vero ratione nam voluptates, modi nobis nihil velit deleniti consectetur libero dolorem ab ea, placeat iste consequuntur sint? Omnis aliquam vel ab.",
            prod_price_1: 10.25,
            prod_price_2: 6.25,
            prod_img:"https://i.ibb.co/YNM8Lvy/chicken-veggie-sharwama.jpg",
        },
        {
            id:6,
            IconFilled: <IoIcons.FilledStar />,
            IconOutline: <IoIcons.OutlineStar />,
            prod_title: "Chicken Sharwama",
            prod_desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia distinctio ipsa illum sequi vero ratione nam voluptates, modi nobis nihil velit deleniti consectetur libero dolorem ab ea, placeat iste consequuntur sint? Omnis aliquam vel ab.",
            prod_price_1: 10.25,
            prod_price_2: 6.25,
            prod_img:"https://i.ibb.co/YNM8Lvy/chicken-veggie-sharwama.jpg",
        },
        {
            id:6,
            IconFilled: <IoIcons.FilledStar />,
            IconOutline: <IoIcons.OutlineStar />,
            prod_title: "Chicken Sharwama",
            prod_desc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia distinctio ipsa illum sequi vero ratione nam voluptates, modi nobis nihil velit deleniti consectetur libero dolorem ab ea, placeat iste consequuntur sint? Omnis aliquam vel ab.",
            prod_price_1: 10.25,
            prod_price_2: 6.25,
            prod_img:"https://i.ibb.co/YNM8Lvy/chicken-veggie-sharwama.jpg",
        },
        ]
    }
]

export default productData;